name: Build Executables

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Compile and Package JAR
        run: |
          mkdir bin
          mkdir jar-in
          javac -d bin src/Main.java src/entities/*.java src/environment/*.java src/utils/*.java
          jar cvfm jar-in/COSMIC-VERTIGO.jar manifest.txt -C bin .

      - name: run jpackage
        run: |
          mkdir dist

          jpackage \
            --input jar-in/ \
            --name "CosmicVertigo" \
            --main-jar "COSMIC-VERTIGO.jar" \
            --main-class "Main" \
            --dest dist \
            --vendor "ethnnnnn" \
            --app-version "${${{ github.ref_name }}#v}" \
            
      - name: upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
          
